version: '3'

services:

  mysql-development:
    platform: linux/x86_64
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
    ports:
      - "3308:3306"